name: Build Executables

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Install Haxe
      uses: HaxeFoundation/haxe-action@v1
      with:
        haxe-version: '4.2.2'
        haxelib-version: '4.1.3'
      
    - name: Install Lime
      run: haxelib install lime
      
    - name: Install OpenFL
      run: haxelib install openfl
      
    - name: Install hxcpp
      run: haxelib install hxcpp
      
    - name: Install Android SDK
      uses: android-actions/setup-android@v2
      with:
        sdk-version: '30'
        
    - name: Build Windows Executable
      run: lime build windows -release
        
    - name: Build Android APK
      run: lime build android -release
        
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Executables
        path: |
          export/windows/bin/MyGame.exe
          export/android/bin/MyGame.apk
