name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Haxe
      uses: HaxeFoundation/haxe-action@v1.1
      with:
        haxe-version: '4.2.3'
    - name: Install OpenFL
      run: haxelib install openfl
    - name: Build Android
      run: openfl build android -release
    - name: Build Windows
      run: openfl build windows -release
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Game artifacts
        path: |
          Export/windows/bin/BACKROOMS1.exe
          Export/android/bin/BACKROOMS1.apk
