name: Build Game

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install OpenFL and HaxeFlixel
      run: |
        haxelib install openfl
        haxelib install flixel
        haxelib run lime setup flixel

    - name: Build APK
      run: lime build android --release

    - name: Build EXE
      run: lime build windows -Dlegacy
